# Generated by Django 5.2.7 on 2025-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('ID_Asesor', models.AutoField(db_column='ID_Asesor', primary_key=True, serialize=False)),
                ('Fecha_reg', models.DateField(blank=True, db_column='Fecha_reg', null=True)),
                ('Hora_reg', models.TimeField(blank=True, db_column='Hora_reg', null=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('Tipo_Documento', models.IntegerField(blank=True, db_column='Tipo_Documento', null=True)),
                ('Cedula', models.CharField(blank=True, db_column='Cedula', max_length=20, null=True)),
                ('Direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('Correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
                ('Fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_nacimiento', null=True)),
                ('Ciudad', models.IntegerField(blank=True, db_column='Ciudad', null=True)),
                ('Departamento', models.IntegerField(blank=True, db_column='Departamento', null=True)),
                ('Edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('Fecha_Ingreso', models.DateField(blank=True, db_column='Fecha_Ingreso', null=True)),
                ('Telefono_personal', models.CharField(blank=True, db_column='Telefono_personal', max_length=50, null=True)),
                ('Cantidad_de_Hijos', models.CharField(blank=True, db_column='Cantidad_de_Hijos', max_length=2, null=True)),
                ('Tipo_de_Sangre', models.IntegerField(blank=True, db_column='Tipo_de_Sangre', null=True)),
                ('Genero', models.IntegerField(blank=True, db_column='Genero', null=True)),
                ('Escolaridad', models.IntegerField(blank=True, db_column='Escolaridad', null=True)),
                ('Estado_Civil', models.IntegerField(blank=True, db_column='Estado_Civil', null=True)),
            ],
            options={
                'db_table': 'asesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargosDistritec',
            fields=[
                ('id_cargo', models.AutoField(db_column='ID_Cargo', primary_key=True, serialize=False)),
                ('cargo', models.CharField(db_column='Cargo', default='0', max_length=50)),
            ],
            options={
                'db_table': 'cargos_distritec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfTrab',
            fields=[
                ('ID_Inf_trab', models.AutoField(db_column='ID_Inf_trab', primary_key=True, serialize=False)),
                ('Codigo_vendedor', models.TextField(blank=True, null=True)),
                ('Cargo', models.IntegerField(blank=True, null=True)),
                ('Carnet', models.IntegerField(blank=True, null=True)),
                ('Fecha_presente', models.DateField(blank=True, null=True)),
                ('Talla', models.IntegerField(blank=True, null=True)),
                ('ID_Area', models.IntegerField(blank=True, null=True)),
                ('Telefono_corporativo', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_corporativo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inf_trab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pri',
            fields=[
                ('ID_Pri', models.AutoField(db_column='ID_Pri', primary_key=True, serialize=False)),
                ('ID_Asesor', models.IntegerField(db_column='ID_Asesor')),
                ('ID_Estado', models.IntegerField(db_column='ID_Estado')),
                ('ID_Inf_trab', models.IntegerField(db_column='ID_Inf_trab')),
            ],
            options={
                'db_table': 'aa_prin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('ID_Sede', models.IntegerField(blank=True, db_column='ID_Sede', null=True)),
            ],
            options={
                'db_table': 'usuario_login',
                'managed': False,
            },
        ),
    ]
