# Generated by Django 5.2.7 on 2025-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesorId', models.CharField(max_length=64)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('diasSemana', models.JSONField(default=dict)),
                ('minutosAdicionales', models.IntegerField(default=0)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('creadaEn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('Cambio de horario', 'Cambio de horario'), ('Minutos adicionales', 'Minutos adicionales')], max_length=32)),
                ('fechaSolicitud', models.DateField()),
                ('nuevoHorario', models.CharField(blank=True, max_length=32, null=True)),
                ('minutos', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=16)),
                ('razonRechazo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
