# Generated by Django 5.2.7 on 2025-11-10 22:00

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionhorario',
            options={'ordering': ['-creada_en']},
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='creadaEn',
            new_name='creada_en',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='horaEntrada',
            new_name='hora_entrada',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='horaSalida',
            new_name='hora_salida',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='minutosAdicionales',
            new_name='minutos_adicionales',
        ),
        migrations.RemoveField(
            model_name='asignacionhorario',
            name='asesorId',
        ),
        migrations.RemoveField(
            model_name='asignacionhorario',
            name='diasSemana',
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='asesor_cargo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='asesor_id',
            field=models.CharField(db_index=True, default=datetime.datetime(2025, 11, 10, 21, 59, 55, 709352, tzinfo=datetime.timezone.utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='asesor_nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='dias_semana',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='asignacionhorario',
            name='lider_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='asignacionhorario',
            index=models.Index(fields=['lider_id', '-creada_en'], name='workforce_a_lider_i_3149d4_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionhorario',
            index=models.Index(fields=['asesor_id'], name='workforce_a_asesor__f2cbad_idx'),
        ),
    ]
