# Generated by Django 5.2.7 on 2025-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_alter_asignacionhorario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='asesor_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_sede',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
