# Generated by Django 5.2.7 on 2025-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_solicitud_asesor_id_solicitud_id_sede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='asesor_id',
            new_name='id_asesor',
        ),
    ]
