# Generated by Django 5.2.7 on 2025-11-11 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_rename_asesor_id_solicitud_id_asesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asesor', models.IntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=160)),
                ('cargo', models.CharField(blank=True, default='', max_length=120)),
                ('id_sede', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('color_hex', models.CharField(default='#6b7280', max_length=7)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('orden', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('limite_minutos_default', models.PositiveIntegerField(blank=True, help_text='Límite diario por estado (minutos). Null = sin límite.', null=True)),
            ],
            options={
                'ordering': ['orden', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='EstadoConfigAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('limite_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('color_hex_override', models.CharField(blank=True, default='', max_length=7)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_estado', to='workforce.asesor')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_asesor', to='workforce.estadotipo')),
            ],
            options={
                'unique_together': {('asesor', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='JornadaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_estado', to='workforce.asesor')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='workforce.estadotipo')),
            ],
            options={
                'indexes': [models.Index(fields=['asesor', 'inicio'], name='workforce_j_asesor__4ff063_idx'), models.Index(fields=['asesor', 'fin'], name='workforce_j_asesor__b434e2_idx')],
            },
        ),
    ]
