# Generated by Django 5.2.7 on 2025-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_asesor_estadotipo_estadoconfigasesor_jornadaestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadotipo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
