# Generated by Django 5.2.7 on 2025-11-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_alter_estadotipo_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jornadaestado',
            name='workforce_j_asesor__4ff063_idx',
        ),
        migrations.RemoveIndex(
            model_name='jornadaestado',
            name='workforce_j_asesor__b434e2_idx',
        ),
        migrations.AddField(
            model_name='jornadaestado',
            name='diferencia_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jornadaestado',
            name='duracion_seg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jornadaestado',
            name='limite_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornadaestado',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.asesor'),
        ),
        migrations.AlterField(
            model_name='jornadaestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.estadotipo'),
        ),
    ]
