# Generated by Django 5.2.7 on 2025-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_remove_jornadaestado_workforce_j_asesor__4ff063_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoconfigasesor',
            name='color_hex_override',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='estadoconfigasesor',
            name='limite_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
