# Generated by Django 5.2.7 on 2025-11-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_alter_estadoconfigasesor_color_hex_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoconfigasesor',
            name='limite_minutos',
        ),
    ]
