# Generated by Django 5.2.7 on 2025-11-14 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_remove_estadoconfigasesor_limite_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fin_real', models.DateTimeField(blank=True, null=True)),
                ('inicio_programado', models.TimeField(blank=True, null=True)),
                ('fin_programado', models.TimeField(blank=True, null=True)),
                ('diferencia_entrada_min', models.IntegerField(blank=True, null=True)),
                ('diferencia_salida_min', models.IntegerField(blank=True, null=True)),
                ('estado_entrada', models.CharField(blank=True, max_length=32, null=True)),
                ('estado_salida', models.CharField(blank=True, max_length=32, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='workforce.asesor')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['asesor', '-fecha'], name='workforce_j_asesor__f72a02_idx')],
                'unique_together': {('asesor', 'fecha')},
            },
        ),
    ]
